//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vn.thanhnu {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceBinding", Namespace="http://devtn.moba.vn/subscription/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback smsKichHoatOperationCompleted;
        
        private System.Threading.SendOrPostCallback smsGiaHanOperationCompleted;
        
        private System.Threading.SendOrPostCallback smsHuyOperationCompleted;
        
        /// <remarks/>
        public Service() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["vn.thanhnu.subrs"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://thanhnu.vn/subscription/subrs.php";
            }
        }
        
        /// <remarks/>
        public event smsKichHoatCompletedEventHandler smsKichHoatCompleted;
        
        /// <remarks/>
        public event smsGiaHanCompletedEventHandler smsGiaHanCompleted;
        
        /// <remarks/>
        public event smsHuyCompletedEventHandler smsHuyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://devtn.moba.vn/subscription/#smsKichHoat", RequestNamespace="http://devtn.moba.vn/subscription/", ResponseNamespace="http://devtn.moba.vn/subscription/")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string smsKichHoat(string User_ID) {
            object[] results = this.Invoke("smsKichHoat", new object[] {
                        User_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsmsKichHoat(string User_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("smsKichHoat", new object[] {
                        User_ID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsmsKichHoat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void smsKichHoatAsync(string User_ID) {
            this.smsKichHoatAsync(User_ID, null);
        }
        
        /// <remarks/>
        public void smsKichHoatAsync(string User_ID, object userState) {
            if ((this.smsKichHoatOperationCompleted == null)) {
                this.smsKichHoatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsmsKichHoatOperationCompleted);
            }
            this.InvokeAsync("smsKichHoat", new object[] {
                        User_ID}, this.smsKichHoatOperationCompleted, userState);
        }
        
        private void OnsmsKichHoatOperationCompleted(object arg) {
            if ((this.smsKichHoatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.smsKichHoatCompleted(this, new smsKichHoatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://devtn.moba.vn/subscription/#smsGiaHan", RequestNamespace="http://devtn.moba.vn/subscription/", ResponseNamespace="http://devtn.moba.vn/subscription/")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string smsGiaHan(string User_ID, string Status) {
            object[] results = this.Invoke("smsGiaHan", new object[] {
                        User_ID,
                        Status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsmsGiaHan(string User_ID, string Status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("smsGiaHan", new object[] {
                        User_ID,
                        Status}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsmsGiaHan(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void smsGiaHanAsync(string User_ID, string Status) {
            this.smsGiaHanAsync(User_ID, Status, null);
        }
        
        /// <remarks/>
        public void smsGiaHanAsync(string User_ID, string Status, object userState) {
            if ((this.smsGiaHanOperationCompleted == null)) {
                this.smsGiaHanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsmsGiaHanOperationCompleted);
            }
            this.InvokeAsync("smsGiaHan", new object[] {
                        User_ID,
                        Status}, this.smsGiaHanOperationCompleted, userState);
        }
        
        private void OnsmsGiaHanOperationCompleted(object arg) {
            if ((this.smsGiaHanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.smsGiaHanCompleted(this, new smsGiaHanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://devtn.moba.vn/subscription/#smsHuy", RequestNamespace="http://devtn.moba.vn/subscription/", ResponseNamespace="http://devtn.moba.vn/subscription/")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string smsHuy(string User_ID) {
            object[] results = this.Invoke("smsHuy", new object[] {
                        User_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsmsHuy(string User_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("smsHuy", new object[] {
                        User_ID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsmsHuy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void smsHuyAsync(string User_ID) {
            this.smsHuyAsync(User_ID, null);
        }
        
        /// <remarks/>
        public void smsHuyAsync(string User_ID, object userState) {
            if ((this.smsHuyOperationCompleted == null)) {
                this.smsHuyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsmsHuyOperationCompleted);
            }
            this.InvokeAsync("smsHuy", new object[] {
                        User_ID}, this.smsHuyOperationCompleted, userState);
        }
        
        private void OnsmsHuyOperationCompleted(object arg) {
            if ((this.smsHuyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.smsHuyCompleted(this, new smsHuyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void smsKichHoatCompletedEventHandler(object sender, smsKichHoatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class smsKichHoatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal smsKichHoatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void smsGiaHanCompletedEventHandler(object sender, smsGiaHanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class smsGiaHanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal smsGiaHanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void smsHuyCompletedEventHandler(object sender, smsHuyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class smsHuyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal smsHuyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
