//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vn.vmgame {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_RegisS2Soap", Namespace="http://tempuri.org/")]
    public partial class Service_RegisS2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterS2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BigPromotionRegisOperationCompleted;
        
        private System.Threading.SendOrPostCallback BigPromotionDeleteOperationCompleted;
        
        /// <remarks/>
        public Service_RegisS2() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["vn.vmgame.Service_RegisS2"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://vmgame.vn/Service_RegisS2.asmx";
            }
        }
        
        /// <remarks/>
        public event RegisterS2CompletedEventHandler RegisterS2Completed;
        
        /// <remarks/>
        public event BigPromotionRegisCompletedEventHandler BigPromotionRegisCompleted;
        
        /// <remarks/>
        public event BigPromotionDeleteCompletedEventHandler BigPromotionDeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterS2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegisterS2(string msisdn) {
            object[] results = this.Invoke("RegisterS2", new object[] {
                        msisdn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterS2(string msisdn, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterS2", new object[] {
                        msisdn}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegisterS2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterS2Async(string msisdn) {
            this.RegisterS2Async(msisdn, null);
        }
        
        /// <remarks/>
        public void RegisterS2Async(string msisdn, object userState) {
            if ((this.RegisterS2OperationCompleted == null)) {
                this.RegisterS2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterS2OperationCompleted);
            }
            this.InvokeAsync("RegisterS2", new object[] {
                        msisdn}, this.RegisterS2OperationCompleted, userState);
        }
        
        private void OnRegisterS2OperationCompleted(object arg) {
            if ((this.RegisterS2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterS2Completed(this, new RegisterS2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BigPromotionRegis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BigPromotionRegis(string msisdn, string code) {
            object[] results = this.Invoke("BigPromotionRegis", new object[] {
                        msisdn,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBigPromotionRegis(string msisdn, string code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BigPromotionRegis", new object[] {
                        msisdn,
                        code}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndBigPromotionRegis(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BigPromotionRegisAsync(string msisdn, string code) {
            this.BigPromotionRegisAsync(msisdn, code, null);
        }
        
        /// <remarks/>
        public void BigPromotionRegisAsync(string msisdn, string code, object userState) {
            if ((this.BigPromotionRegisOperationCompleted == null)) {
                this.BigPromotionRegisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBigPromotionRegisOperationCompleted);
            }
            this.InvokeAsync("BigPromotionRegis", new object[] {
                        msisdn,
                        code}, this.BigPromotionRegisOperationCompleted, userState);
        }
        
        private void OnBigPromotionRegisOperationCompleted(object arg) {
            if ((this.BigPromotionRegisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BigPromotionRegisCompleted(this, new BigPromotionRegisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BigPromotionDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BigPromotionDelete(string msisdn, string code) {
            object[] results = this.Invoke("BigPromotionDelete", new object[] {
                        msisdn,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBigPromotionDelete(string msisdn, string code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BigPromotionDelete", new object[] {
                        msisdn,
                        code}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndBigPromotionDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BigPromotionDeleteAsync(string msisdn, string code) {
            this.BigPromotionDeleteAsync(msisdn, code, null);
        }
        
        /// <remarks/>
        public void BigPromotionDeleteAsync(string msisdn, string code, object userState) {
            if ((this.BigPromotionDeleteOperationCompleted == null)) {
                this.BigPromotionDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBigPromotionDeleteOperationCompleted);
            }
            this.InvokeAsync("BigPromotionDelete", new object[] {
                        msisdn,
                        code}, this.BigPromotionDeleteOperationCompleted, userState);
        }
        
        private void OnBigPromotionDeleteOperationCompleted(object arg) {
            if ((this.BigPromotionDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BigPromotionDeleteCompleted(this, new BigPromotionDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RegisterS2CompletedEventHandler(object sender, RegisterS2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterS2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterS2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BigPromotionRegisCompletedEventHandler(object sender, BigPromotionRegisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BigPromotionRegisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BigPromotionRegisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BigPromotionDeleteCompletedEventHandler(object sender, BigPromotionDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BigPromotionDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BigPromotionDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
